### ISSUE TITLE
AlgorithmExecution FileVLLoad(afdx.vl) raises java.nio.file.InvalidPathException exception on (Windows 10)

### ISSUE THREAD

**Issue by daniel3097** [girtel/Net2Plan-AFDX#2]
Details from net2plan Java console (Windows enviroment):

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /G:/net2plan-0.4.2/net2plan-0.4.2/workspace/0_VL.csv
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.nio.file.Paths.get(Unknown Source)
	at afdx.vl.FileVLLoad.executeAlgorithm(FileVLLoad.java:39)
	at com.net2plan.gui.tools.GUINetworkDesign.execute(GUINetworkDesign.java:141)
	at com.net2plan.gui.utils.ThreadExecutionController$SwingWorkerCompletionWaiter.doInBackground(ThreadExecutionController.java:196)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Tue Jun 20 22:59:50 CEST 2017

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /G:/net2plan-0.4.2/net2plan-0.4.2/workspace/0_VL.csv
sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
sun.nio.fs.WindowsPathParser.parse(Unknown Source)
sun.nio.fs.WindowsPathParser.parse(Unknown Source)
sun.nio.fs.WindowsPath.parse(Unknown Source)
sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
java.nio.file.Paths.get(Unknown Source)
afdx.vl.FileVLLoad.executeAlgorithm(FileVLLoad.java:39)

I guess this is the same issue as disscussed here 
 https://stackoverflow.com/questions/9834776/java-nio-file-path-issue

**Comment by laureanofo** [comment]
Dear Daniel,

I have been very busy this week, sorry for my late answer. I thinks your problem is you need to put the files in the right place. You need to create 3 files containing the info form the configuration table, 0_VL.csv is one of them. In Net2Plan-AFDX/configuration_tables/ you have some examples files, they have to be place in the same folder than de .jar. Try and let me know.

Best reagards.

**Comment by daniel3097** [comment]
Hi laureanofo,

The file is not the problem - the files are/were there: 
 Verzeichnis von G:\net2plan-0.4.2\net2plan-0.4.2\workspace

19.06.2017  23:20    <DIR>          .
19.06.2017  23:20    <DIR>          ..
16.06.2017  11:37               120 0_ES.csv
16.06.2017  11:37               120 0_ES_TEST_001.csv
16.06.2017  11:37               211 0_TOPOLOGY.csv
16.06.2017  11:37               211 0_TOPOLOGY_TEST_001.csv
16.06.2017  11:37               204 0_VL.csv
16.06.2017  11:37               204 0_VL_TEST_001.csv
19.06.2017  23:45         5'580'322 ADFX.jar
19.06.2017  23:16         1'361'531 BuiltInExamples.jar
19.06.2017  23:20    <DIR>          configuration_tables
19.06.2017  23:16    <DIR>          data
               8 Datei(en),      6'942'923 Bytes
               4 Verzeichnis(se), 514'804'416'512 Bytes frei

Similar issue in class FileESLoad - let me explain my hack in  class FileESLoad;

public class FileESLoad implements IAlgorithm {
	private InputParameter fileName = new InputParameter(AFDXParameters.SIM_FILE_NAME, "", "");

	@Override
	public String executeAlgorithm(NetPlan netPlan, Map<String, String> algorithmParameters,
			Map<String, String> net2planParameters) {

		String fileName = "0_ES.csv";
		String folderName = algorithmParameters.get(AFDXParameters.SIM_FILE_NAME);
		fileName = (!folderName.equals("")
				? AFDXParameters.CONFIGURATION_TABLES_FOLDER + File.separator + folderName + File.separator : "")
				+ fileName;

		double lengthInKm = 0.05;// 50 meters
		int space = 100;

		String path = getClass().getProtectionDomain().getCodeSource().getLocation().getPath();
		path = path.substring(0, path.lastIndexOf("/") + 1);
		
		System.out.println("Path " + path);
		
		// https://stackoverflow.com/questions/9834776/java-nio-file-path-issue
		path = path.replaceFirst("^/(.:/)", "$1");
		System.out.println("Path " + path);


now evereything is fine - Net2Plan Java console output shows what happens:
Path /G:/net2plan-0.4.2/net2plan-0.4.2/workspace/
Path G:/net2plan-0.4.2/net2plan-0.4.2/workspace/

Probably that's the time when I should learn to provide proper patches for fixed issues .... .

Regards
Daniel

**Comment by laureanofo** [comment]
Hola.

Acabo de firmar la petición "Gobierno de España: SOS Mar Menor!!!" y pensé
que te podría interesar.

Estamos intentando conseguir 7.500 firmas y necesitamos todo el apoyo que
podamos conseguir. Puedes leer más y firmar la petición aquí:

http://chng.it/HWVVqnxD5C

¡Gracias!
Laureano
